### ISSUE TITLE
Comparison to python-ternay

### ISSUE THREAD

**Issue by jan-janssen** [yuzie007/mpltern#1]
Hi @yuzie007,

I was using https://github.com/marcharper/python-ternary before, can you maybe briefly explain to me what is the difference to your library? Looking at your documentation, yours seem to be more closely oriented on matplotlib, but maybe you can give me some more details. 

Best, 

Jan

**Comment by yuzie007** [comment]
Hi @jan-janssen,

Thanks for your curiosity. I know of course https://github.com/marcharper/python-ternary, which is a great code supporting ternary plots in Python long time. My code focuses on inheriting Matplotlib "behaviors" as much as possible. This includes e.g.:

- Default spaces between tick markers and tick labels; as far as you like Matplotlib spacing, you may also like mpltern default (I hope)
- Automatic tick locations based on Matplotlib (as far as I know python-ternary must specify by hand)
- Consistent method names with Matplotlib as much as possible (as far as I know python-ternary often has its own method names and requires to learn it)
- Since it depends on Matplotlib defaults, switching e.g. to seaborn styles is straightforward

So, actually for this code I focuses on not adding new fancy plotting styles but e.g. to give consistent behaviors with Matplotlib. For people who do not care it, my code might be no fancy at all.

I also focuses on to make it work also in interactive modes; if in case you have some curiosity it might be also nice to try my code in Jupyter notebooks and e.g. zoom-in. Hopefully you'll see an expected behavior, which python-ternary might not do.

These are, however, just my own opinions, so I know nothing how others feel.
